version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: mediqueue-postgres
    environment:
      POSTGRES_DB: hospital_queue
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: mediqueue-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/hospital_queue
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SERVER_PORT: 8081
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
    container_name: mediqueue-frontend
    depends_on:
      - backend
    environment:
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
